config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  post '/users/confirm_email' => 'users#confirm_email'

  concern :votable do
    post :vote, on: :member
  end

  concern :commentable do
    resources :comments, shallow: true, only: [:create]
  end

  resources :questions, concerns: [:votable, :commentable] do
    member do
      delete :destroy_file
    end
    resources :answers, shallow: true, only: [:create, :update, :new, :destroy], concerns: [:votable, :commentable] do
      member do
        post :mark_as_best
        delete :destroy_file
      end
    end

    resources :subscriptions, shallow: true, only: %i[create destroy]
  end


  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show update create destroy] do
        resources :answers, shallow: true, only: %i[index show update create destroy]
      end
    end
  end

  resources :rewards, only: [:index]
  resources :links, only: [:destroy]
  root to: "questions#index"

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_many :subscriptions, dependent: :destroy

  has_one :reward, dependent: :destroy

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :reward, reject_if: :all_blank

  belongs_to :user
  belongs_to :best_answer, class_name: 'Answer', optional: true

  validates :title, :body, presence: true
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  protect_from_forgery with: :null_session, only: %i[update create destroy]
  skip_authorization_check

  def index
    @questions = Question.all
    render json: @questions
  end

  def show
    render json: question, serializer: QuestionSeparateSerializer
  end

  def create
    @question = current_resource_owner.questions.new(question_params)

    if @question.save
      render json: @question, status: :created
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def update
    authorize! :update, question

    if question.update(question_params)
      render json: question, status: :created
    else
      render json: { errors: 'Question not update' }, status: :unprocessable_entity
    end
  end

  def destroy
    authorize! :destroy, question

    question.destroy
    render json: { messages: ['Question destroy'] }
  end

  private

  def question
    @question ||= Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_question, only: [:show, :update, :destroy, :destroy_file]
  after_action :publish_question, only: [:create]

  include Voted

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    @best_answer = @question.best_answer
    @other_answers = @question.answers.where.not(id: @question.best_answer_id)
    @answer = Answer.new
    @answer.links.new
    gon.question_id = @question.id
    gon.user_id = current_user&.id
    @question_comment = @question.comments.new
    @answer_comment = @answer.comments.new
    @subscription = @question.subscriptions.find_by(user: current_user)
  end

  def new
    @question = Question.new
    @question.links.new
    @question.build_reward
  end

  def edit
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    if current_user.author_of?(@question)
      @question.update(question_params)
    end
  end

  def destroy
    if current_user.author_of?(@question)
      @question.destroy

      redirect_to questions_path, notice: 'Question successfully deleted.'
    else
      redirect_to questions_path
    end
  end

  def destroy_file
    if current_user.author_of?(@question)
      @file = ActiveStorage::Attachment.find(params[:file_id])
      @file.purge
    end
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast('questions_channel',
       ApplicationController.render(partial: 'questions/question_preview',
                                    locals: { question: @question })
    )
  end

  private

  def find_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(
      :title,
      :body,
      files: [],
      links_attributes: [:id, :name, :url, :_destroy],
      reward_attributes: [:title, :image_url]
    )
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_link_fields.html.slim
.nested-fields
  .field
    p
      = f.label :name, 'Link name'
      = f.text_field :name
  .field
    p
      = f.label :url
      = f.text_field :url
  = link_to_remove_association "remove link", f

app/views/questions/_question.html.slim
- cache question do
  h1= question.title
  p= question.body
  - if question.files.attached?
    - question.files.each do |file|
      div id = "question-file-#{file.id}"
        p = link_to file.filename.to_s, url_for(file)
        - if can?(:destroy_file, question)
          p = link_to 'Delete file', destroy_file_question_path(question, file_id: file.id), method: :delete, remote: true
  .links
    h4 Links:
    ul
      = render @question.links
  = render 'votes', resource: @question
  - if question.reward
    p Reward:
    p = @question.reward.title
    image src="#{@question.reward.image_url}" style="width:48px;height:48px;"

  - if @subscription.present?
    - if can?(:destroy, @subscription)
      = link_to 'Unsubscribe', question_subscriptions_path(@question, @subscription), method: :delete
  - else
    - if can?(:create, Subscription)
      = link_to 'Subscribe', question_subscriptions_path(@question), method: :post

  - if can?(:update, question)
    p = link_to 'Edit question', '#', class: 'edit-question-link'
  - if can?(:destroy, question)
    p = link_to 'Delete question', question_path(question), method: :delete

  = form_with model: question, class: 'hidden', html: { id: "edit-question" }, local: false do |f|
    p
      = f.label :body, 'Your title'
      = f.text_field :title
    p
      = f.label :body, 'Your question'
      = f.text_area :body
    p
      = f.label :files
      = f.file_field :files, multiple: true, direct_upload: true

    p Links:
    #links
      = f.fields_for :links do |link|
        = render 'link_fields', f: link
      .links
        = link_to_add_association 'add link', f, :links

      = f.submit 'Save'

app/views/questions/_question_preview.html.slim
p = link_to question.title, question

app/views/questions/destroy_file.js.erb
$('#question-file-' + <%= @file.id %>).remove();

app/views/questions/index.html.slim
.questions
  = render partial: 'questions/question_preview', collection: @questions, as: :question

p= link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question

= form_with model: @question, local: true do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true

  p Links:
  #links
    = f.fields_for :links do |link|
      = render 'link_fields', f: link
    .links
      = link_to_add_association 'add link', f, :links

  p Reward:
  #reward
    = f.fields_for :reward do |r|
      p
        = r.label :title, 'Reward name'
        = r.text_field :title
      p
        = r.label :image, 'Reward image'
        = r.text_field :image_url

  p= f.submit 'Ask'

app/views/questions/show.html.slim
div id="question-#{@question.id}"
  = render @question
  = link_to 'Rewards', rewards_path

  .comments
    h3 Comments:
    = render @question.comments

    - if current_user
      = render 'comments/form', commentable: @question, comment: @question_comment

  .comment-errors
    = render 'shared/errors',  resource: @comment

  .question-errors
    = render 'shared/errors', resource: @question

.answer-errors
  = render 'shared/errors', resource: @answer

.answers
  .best_answer
    - if @question.best_answer
      p = 'Best answer:'
      = render @best_answer
  .other_answer
    p = 'Answers:'
    = render @other_answers

= render 'answers/form'

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: @question %>');

<% if !@question.errors.present? %>
$('.question').html('<%= j render @question %>');

<% end %>