config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  post '/users/confirm_email' => 'users#confirm_email'

  concern :votable do
    post :vote, on: :member
  end

  concern :commentable do
    resources :comments, shallow: true, only: [:create]
  end

  resources :questions, concerns: [:votable, :commentable] do
    member do
      delete :destroy_file
    end
    resources :answers, shallow: true, only: [:create, :update, :new, :destroy], concerns: [:votable, :commentable] do
      member do
        post :mark_as_best
        delete :destroy_file
      end
    end

    resources :subscriptions, shallow: true, only: %i[create destroy]
  end


  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show update create destroy] do
        resources :answers, shallow: true, only: %i[index show update create destroy]
      end
    end
  end

  resources :rewards, only: [:index]
  resources :links, only: [:destroy]
  root to: "questions#index"

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user
  has_many :links, dependent: :destroy, as: :linkable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :body, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new, :destroy]
  before_action :find_question, only: [:new, :create]
  before_action :set_answer, only: [:destroy, :update, :mark_as_best, :destroy_file]
  after_action :publish_answer, only: [:create]

  include Voted

  authorize_resource

  def new
    @answer = @question.answers.new
  end

  def create
    @answer = @question.answers.create(answer_params)
    @answer.user = current_user

    @answer.save

    @answer_comment = @answer.comments.new
  end

  def update
    @answer.update(answer_params)
    @question = @answer.question
  end

  def destroy
    if current_user.author_of?(@answer)
      @answer.destroy

    else
      redirect_to questions_path(@answer.question)
    end
  end

  def mark_as_best
    @last_best_answers = @answer.question.best_answer
    @answer.question.update(best_answer_id: @answer.id)
    if @answer.question.reward
      @answer.question.reward.update(user: @answer.user)
    end
  end

  def destroy_file
    if current_user.author_of?(@answer)
      @file = ActiveStorage::Attachment.find(params[:file_id])
      @file.purge
    end
  end

  def publish_answer
    html = ApplicationController.renderer.new(warden: warden).render(
      partial: 'answers/answer_simple',
      locals: { answer: @answer }
    )

    ActionCable.server.broadcast(
      "question_#{@question.id}",
      { html:, author_id: @answer.user.id }
    )
  end

  private

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:id, :name, :url, :_destroy])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  protect_from_forgery with: :null_session, only: %i[update create destroy]
  skip_authorization_check

  def index
    @answers = question.answers
    render json: @answers
  end

  def show
    render json: answer, serializer: AnswerSeparateSerializer
  end

  def create
    @answer = questions.answers.new(answer_params.merge(user: current_resource_owner))

    if @answer.save
      render json: @answer, status: :created
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def update
    authorize! :update, answer

    if answer.update(answer_params)
      render json: answer, status: :created
    else
      render json: { errors: 'Answer not update' }, status: :unprocessable_entity
    end
  end

  def destroy
    authorize! :destroy, answer

    answer.destroy
    render json: { messages: ['Answer destroy'] }
  end


  private

  def question
    @question ||= Question.find(params[:question_id])
  end

  def answer
    @answer ||= Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache answer do
  div id="answer-#{answer.id}"
    p = answer.body
    - if answer.files.attached?
      - answer.files.each do |file|
        div id = "answer-file-#{file.id}"
          p = link_to file.filename.to_s, url_for(file)
          - if can?(:destroy_file, answer)
            p = link_to 'Delete file', destroy_file_answer_path(answer, file_id: file.id), method: :delete, remote: true
    .links
      h4 Links:
      ul
        = render answer.links
    = render 'votes', resource: answer
    .comments
      h4 Comments:
      = render answer.comments

        - if current_user
          = render 'comments/form', commentable: answer, comment: @answer_comment
    - if can?(:update, answer)
      p = link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
      - if can?(:destroy, answer)
      p = link_to 'Delete answer', answer, method: :delete, remote: true
    - if can?(:mark_as_best, answer)
      p = link_to 'Mark as best', mark_as_best_answer_path(answer), class: 'best_answer_link', method: :post, remote: true

      .comment-errors
        = render 'shared/errors', resource: @comment

    .answer-errors
      = render 'shared/errors', resource: @answer

    = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" }, local: false  do |f|
      p
        = f.label :body, 'Your answer'
        = f.text_area :body
      p
        = f.label :files
        = f.file_field :files, multiple: true, direct_upload: true

      p Links:
      #links
        = f.fields_for :links do |link|
          = render 'link_fields', f: link
        .links
          = link_to_add_association 'add link', f, :links

      p= f.submit 'Save'

app/views/answers/_answer_simple.html.slim
div id="answer-#{answer.id}"
  p = answer.body
  - if answer.files.attached?
    - answer.files.each do |file|
      div id = "answer-file-#{file.id}"
        p = link_to file.filename.to_s, url_for(file)

  .links
    h4 Links:
    ul
      = render answer.links
    = render 'votes', resource: answer
  .comments
    h4 Comments:
    = render answer.comments
  .answer-errors
    = render 'shared/errors', resource: @answer

app/views/answers/_form.html.slim
= form_with model: [@question, @answer], local: false do |f|
  p
  = f.label :body
  = f.text_area :body
  p
  = f.label :files
  = f.file_field :files, multiple: true

  p Links:
  #links
    = f.fields_for :links do |link|
      = render 'link_fields', f: link
    .links
      = link_to_add_association 'add link', f, :links

  p= f.submit 'Add an answer'

app/views/answers/_link_fields.html.slim
.nested-fields
  .field
    p
      = f.label :name, 'Link name'
      = f.text_field :name
  .field
    p
      = f.label :url
      = f.text_field :url
  = link_to_remove_association "remove link", f

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$('#answer-' + <%= @answer.id %>).remove();

app/views/answers/destroy_file.js.erb
$('#answer-file-' + <%= @file.id %>).remove();

app/views/answers/mark_as_best.js.erb
<% if @last_best_answers %>
$('.other_answer').append('<%= j render @last_best_answers %>');
<% end %>
$('.other_answer #answer-' + <%= @answer.id %>).remove();
$('.best_answer').html("<p>Best answer:</p><%= j render @answer %>");

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if !@answer.errors.present? %>
$('.answers').html('<%= j render @question.answers %>');

<% end %>